Bill Print Program
dynamicdev4all/RDEC-SEC-D pull request #1
Opened 2024-10-21 15:39 UTC by siddharthsharmae

2024-10-22 03:37 UTC, dynamicdev4all requested changes
LGTM, properties file has whitespaces. Please remove them.

2024-10-22 03:38 UTC, dynamicdev4all requested changes
Please have a look on the properties file there should be no whitespaces.

2024-10-23 07:38 UTC, siddharthsharmae commented
Done sir

2024-11-07 05:52 UTC, dynamicdev4all approved these changes

2024-11-07 05:53 UTC, merged